---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: name
        image: jondlm/nodeapp
        resources:
          requests:
            cpu: 0.1
            memory: 200Mi
          limits:
            cpu: 1
            memory: 500Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nodeapp

